### ISSUE TITLE
CovarianceMatrix can't get the symmetric matrix

### ISSUE THREAD

**Issue by xiajohnnyxia** [gonum/stat#190] opened 2018-01-04 23:32 UTC
```
X :=  []float64{0,2,
		1,1,
		2,0,}
```
I use `stat.CovarianceMatrix(nil,mat.NewDense(3,2, X),nil)` in order to caculate the covariance of matrix.But i can't get the symmetric matrix.The result is `[1 -1 0 1]` not the `[1 -1 -1 1]`.What's wrong with it?And many others tests like this.

**Comment by kortschak** [comment] 2018-01-04 23:51
Please take this issue to gonum/gonum. The gonum/stat package is deprecated and in the process of being archived. Providing a complete reproducer would be helpful.

However, it looks like you are not using the API correctly.

```
~ $ cat cov.go 
package main

import (
	"fmt"

	"gonum.org/v1/gonum/mat"
	"gonum.org/v1/gonum/stat"
)

func main() {
	fmt.Println(mat.Formatted(stat.CovarianceMatrix(nil, mat.NewDense(3, 2, []float64{
		0, 2,
		1, 1,
		2, 0,
	}), nil)))
}
~ $ go run cov.go 
⎡ 1  -1⎤
⎣-1   1⎦
```

The backing data for the `*mat.SymDense` does not keep both triangles of the symmetric matrix since it does not need to.

>And many others tests like this.

This is unhelpfully broad. If there are other problems, please file them as separate issues or at the very least provide explanations for what they are.

I'll close this now. If you still have problems file the issue at gonum/gonum.

**Closed by kortschak** 2018-01-04 23:51 UTC

**Comment by xiajohnnyxia** [comment] 2018-01-05 22:54
Ok,Thank you and it's work.It's the first time i used this type.

**Comment by kortschak** [comment] 2018-01-05 23:02
No worries. In general don't access the data in the backing slice except via the mat API. If you do, make sure your read the documentation in gonum.org/v1/gonum/blas/blas64 (for the types) and gonum.org/v1/gonum/blas/gonum for the memory layout.
